name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Install
        run: npm install


      - name: Lint & Compile
        run: npm run compile
      
      - name: Package
        run: |
          npm install -g vsce
          vsce package
