name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Lint & Compile
        run: npm run compile

      - name: Package
        run: |
          npm install -g @vscode/vsce
          vsce package
          unzip -l *.vsix
